/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiIndexRouteImport } from './routes/wiki/index'
import { Route as MacrosIndexRouteImport } from './routes/macros/index'
import { Route as EditorIndexRouteImport } from './routes/editor/index'
import { Route as MacrosUuidRouteImport } from './routes/macros/$uuid'
import { Route as EditorDefSlugRouteImport } from './routes/editor/$defSlug'
import { Route as DefDefSlugRouteImport } from './routes/def.$defSlug'
import { Route as DefDefSlugFormulationRefRouteImport } from './routes/def.$defSlug_.$formulationRef'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => rootRouteImport,
} as any)
const MacrosIndexRoute = MacrosIndexRouteImport.update({
  id: '/macros/',
  path: '/macros/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => rootRouteImport,
} as any)
const MacrosUuidRoute = MacrosUuidRouteImport.update({
  id: '/macros/$uuid',
  path: '/macros/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorDefSlugRoute = EditorDefSlugRouteImport.update({
  id: '/editor/$defSlug',
  path: '/editor/$defSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DefDefSlugRoute = DefDefSlugRouteImport.update({
  id: '/def/$defSlug',
  path: '/def/$defSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DefDefSlugFormulationRefRoute =
  DefDefSlugFormulationRefRouteImport.update({
    id: '/def/$defSlug_/$formulationRef',
    path: '/def/$defSlug/$formulationRef',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/signin': typeof SigninRoute
  '/def/$defSlug': typeof DefDefSlugRoute
  '/editor/$defSlug': typeof EditorDefSlugRoute
  '/macros/$uuid': typeof MacrosUuidRoute
  '/editor/': typeof EditorIndexRoute
  '/macros/': typeof MacrosIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/def/$defSlug/$formulationRef': typeof DefDefSlugFormulationRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/signin': typeof SigninRoute
  '/def/$defSlug': typeof DefDefSlugRoute
  '/editor/$defSlug': typeof EditorDefSlugRoute
  '/macros/$uuid': typeof MacrosUuidRoute
  '/editor': typeof EditorIndexRoute
  '/macros': typeof MacrosIndexRoute
  '/wiki': typeof WikiIndexRoute
  '/def/$defSlug/$formulationRef': typeof DefDefSlugFormulationRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/signin': typeof SigninRoute
  '/def/$defSlug': typeof DefDefSlugRoute
  '/editor/$defSlug': typeof EditorDefSlugRoute
  '/macros/$uuid': typeof MacrosUuidRoute
  '/editor/': typeof EditorIndexRoute
  '/macros/': typeof MacrosIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/def/$defSlug_/$formulationRef': typeof DefDefSlugFormulationRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/signin'
    | '/def/$defSlug'
    | '/editor/$defSlug'
    | '/macros/$uuid'
    | '/editor/'
    | '/macros/'
    | '/wiki/'
    | '/def/$defSlug/$formulationRef'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/signin'
    | '/def/$defSlug'
    | '/editor/$defSlug'
    | '/macros/$uuid'
    | '/editor'
    | '/macros'
    | '/wiki'
    | '/def/$defSlug/$formulationRef'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/signin'
    | '/def/$defSlug'
    | '/editor/$defSlug'
    | '/macros/$uuid'
    | '/editor/'
    | '/macros/'
    | '/wiki/'
    | '/def/$defSlug_/$formulationRef'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  SigninRoute: typeof SigninRoute
  DefDefSlugRoute: typeof DefDefSlugRoute
  EditorDefSlugRoute: typeof EditorDefSlugRoute
  MacrosUuidRoute: typeof MacrosUuidRoute
  EditorIndexRoute: typeof EditorIndexRoute
  MacrosIndexRoute: typeof MacrosIndexRoute
  WikiIndexRoute: typeof WikiIndexRoute
  DefDefSlugFormulationRefRoute: typeof DefDefSlugFormulationRefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/wiki'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/macros/': {
      id: '/macros/'
      path: '/macros'
      fullPath: '/macros/'
      preLoaderRoute: typeof MacrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/': {
      id: '/editor/'
      path: '/editor'
      fullPath: '/editor/'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/macros/$uuid': {
      id: '/macros/$uuid'
      path: '/macros/$uuid'
      fullPath: '/macros/$uuid'
      preLoaderRoute: typeof MacrosUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$defSlug': {
      id: '/editor/$defSlug'
      path: '/editor/$defSlug'
      fullPath: '/editor/$defSlug'
      preLoaderRoute: typeof EditorDefSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/def/$defSlug': {
      id: '/def/$defSlug'
      path: '/def/$defSlug'
      fullPath: '/def/$defSlug'
      preLoaderRoute: typeof DefDefSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/def/$defSlug_/$formulationRef': {
      id: '/def/$defSlug_/$formulationRef'
      path: '/def/$defSlug/$formulationRef'
      fullPath: '/def/$defSlug/$formulationRef'
      preLoaderRoute: typeof DefDefSlugFormulationRefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  SigninRoute: SigninRoute,
  DefDefSlugRoute: DefDefSlugRoute,
  EditorDefSlugRoute: EditorDefSlugRoute,
  MacrosUuidRoute: MacrosUuidRoute,
  EditorIndexRoute: EditorIndexRoute,
  MacrosIndexRoute: MacrosIndexRoute,
  WikiIndexRoute: WikiIndexRoute,
  DefDefSlugFormulationRefRoute: DefDefSlugFormulationRefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
